name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to server
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
        run: |
          echo "Deploying to $SERVER_URL"
          # Add deployment commands here
